CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50), email VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), description TEXT);
CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, category_id INT, name VARCHAR(100), price DECIMAL(10,2), stock INT, FOREIGN KEY (category_id) REFERENCES categories(id));
CREATE TABLE orders (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, status VARCHAR(20), total_amount DECIMAL(10,2), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE order_items (id INT AUTO_INCREMENT PRIMARY KEY, order_id INT, product_id INT, quantity INT, unit_price DECIMAL(10,2), FOREIGN KEY (order_id) REFERENCES orders(id), FOREIGN KEY (product_id) REFERENCES products(id));
CREATE TABLE reviews (id INT AUTO_INCREMENT PRIMARY KEY, product_id INT, user_id INT, rating INT, comment TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (product_id) REFERENCES products(id), FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE carts (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE cart_items (id INT AUTO_INCREMENT PRIMARY KEY, cart_id INT, product_id INT, quantity INT, FOREIGN KEY (cart_id) REFERENCES carts(id), FOREIGN KEY (product_id) REFERENCES products(id));
CREATE TABLE payments (id INT AUTO_INCREMENT PRIMARY KEY, order_id INT, amount DECIMAL(10,2), method VARCHAR(50), status VARCHAR(20), payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (order_id) REFERENCES orders(id));
CREATE TABLE shipments (id INT AUTO_INCREMENT PRIMARY KEY, order_id INT, tracking_number VARCHAR(100), carrier VARCHAR(50), status VARCHAR(20), FOREIGN KEY (order_id) REFERENCES orders(id));
